travis:
  secure:
    BINSTAR_TOKEN: KYtR/VIwwzFksrTbbAKnqW8qFVABjnSKBzra704i4ts/xsZGUtPdLJMDcM9J4yYvRAkRE5r8eKc4K9tckzbeg0UX/yvvjcO2CxJiCoPGfUN20t0CF1nJnTNWM19nhIYFueA5PLvhmbUBG/uB/7EwVaDjYjhNSbiDBQn03OdyKXVYSdRLYvnRRQAQly2D5jG04knkwRwr9Bv0emlwHwWsFAPUpxMnInLtJbT4Cz7ll3H5vHN+OnZpWCge7BXBS//OuE0Ztvk4nXonSIKC1o4uu387PiVwclGfVEuSSdELm2qWA7zn55WdImzdQEFd6pZBeihxCHRtOcZBChYgrKHTR0rKp1pZ8/GqtRaMlikcLkbptHXJ71AhLtkNexxqrtrskgb8UvkmuIYON7nb8hC50z9DS58eQXpBEnZUpRrL5IbN0hB5iyROqEBOwcoHwtu2k6PSC0zFISIMIldJuz9XJVkGUTI3vbBasyblSUmgdSOLclOQS7kkAfhQ3PuLx6BRyABJYcosvVbE94V154hWnN1CGJqsxbX6LpdQEoMmDGVJywRXvSBDL3RJXimhu3BAYvxQPiDYAFUhaIWwCDOVPxJJiFbIwVg5iAvpgwWviX1fKE8z3BAF2cFf2wRfdri/hdodRkoK7Gp5hWcxD4cUslDOLesxlbzLj1mhec9rq2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
